data_source dbsource:  
    type: snowflake
    account: qy50257.central-india.azure
    username: VISHNUPRASATH19
    password: Vishnu@19
    role: accountadmin
    database: SNOWFLAKE_SAMPLE_DATA
    warehouse: compute_wh
    schema: TPCH_SF1
    threads: 10
    client_session_keep_alive: False
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: d83734b5-716a-4128-9640-923b72e1cb3f
  api_key_secret: 55aPWDgQni5PrzyPIUFi8rYtPUQnC4ibz0niYgFvCxqyTCjWF8YWAQT    
