name: Scan for data quality

on: pull_request

jobs:
  soda_scan:
    runs-on: windows-latest
    name: Run Soda Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Perform Soda Scan
        uses: sodadata/soda-github-action@v1.0.2
        with:
          soda_library_version: v1.5.5
          data_source: snowflake
          configuration: ./configuration.yml
          checks: ./checks.yml
        env:
          SODA_CLOUD_API_KEY: 83734b5-716a-4128-9640-923b72e1cb3f
          SODA_CLOUD_API_SECRET: 55aPWDgQni5PrzyPIUFi8rYtPUQnC4ibz0niYgFvCxqyTCjWF8YWAQT
          SNOWFLAKE_USERNAME: VISHNUPRASATH19
          SNOWFLAKE_PASSWORD: Vishnu@19
